name: Automate Deployment for Next.js

on:
  push:
    branches:
      - dev  # Specify the branch that triggers the workflow (change if needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Updated version of checkout action

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the version of Node.js you need

      - name: Install Dependencies
        run: npm install  # Install the Node.js dependencies for your Next.js project

      - name: Build Next.js App
        run: npm run build  # Build the Next.js application

      - name: Deploy to cPanel
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          port: 17177  # Specify your cPanel SSH port
          script: |
            export TERM=xterm
            cd /home/${{ secrets.CPANEL_USERNAME }}/public_html/nextjs-app  # Change this path to your deployment directory
            # Remove previous build files
            rm -rf .next static  # Adjust these as per your project's folder structure
            
            # Pull the latest changes
            git reset --hard
            git pull origin dev

            # Copy the new build files from the GitHub Actions runner to your cPanel server
            rsync -avz --exclude=node_modules/ --exclude=.git/ ./ ./

            # Install production dependencies (you can skip devDependencies)
            npm install --production

            # Optionally, you can restart any running services if applicable
            pm2 restart nextjs-app  # Adjust based on your deployment method
            

      - name: Notify on success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          fields: repo,commit
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_USERNAME: 'Deployment Bot'

      - name: Notify on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: repo,commit
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_USERNAME: 'Deployment Bot'
git init
