name: Automate Deployment for Next.js

on:
  push:
    branches:
      - dev  # Trigger the workflow on push to the 'dev' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3  # Use the latest version

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version your Next.js app requires

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install  # Install dependencies for the Next.js app

      # Step 4: Build Next.js App
      - name: Build Next.js App
        run: npm run build  # Build the Next.js app

      # Step 5: Deploy to cPanel via SSH
      - name: Deploy to cPanel via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}  # Your cPanel host or IP
          username: ${{ secrets.CPANEL_USERNAME }}  # Your cPanel username
          password: ${{ secrets.CPANEL_PASSWORD }}  # Your cPanel password
          port: 17177  # Your cPanel SSH port (usually 22, adjust as needed)
          script: |
            export TERM=xterm
            cd /home/techozon/deploynextapp.techozon.com  # Update with your correct directory
            # Remove previous build files
            rm -rf .next static

            # Pull the latest changes from the dev branch
            git reset --hard
            git pull origin dev

            # Sync local files to the cPanel server
            rsync -avz --exclude=node_modules/ --exclude=.git/ ./ ./

            # Install production dependencies
            npm install --production

            # Optionally, restart any services if necessary (e.g., pm2)
            pm2 restart nextjs-app  # Adjust if needed

      # Step 6: Notify on Success
      - name: Notify on Success
        if: success()
        run: echo "Deployment successful!"

      # Step 7: Notify on Failure
      - name: Notify on Failure
        if: failure()
        run: echo "Deployment failed!"

